INSERT INTO role (id_role, name) VALUES
(1, 'Obiwan Kenobi'),
(2, 'Qui Jon Jim'),
(3, 'Princess Amidala'),
(4, 'Dr Jones (indy)'),
(5, 'Marion Ravenwood'),
(6, 'Marcus Brody'),
(7, 'Bruce Wayne (Batman)'),
(8,  'Joker'),
(9, 'Vicki Vale'),
(10, 'Professeur Charles Xavier'),
(11, 'Logan'),
(12, 'Magnetto'),
(13, 'Walt Kowalski'),
(14, 'Mad Max'),
(15, 'Tristan Ludlow'),
(16, 'William Ludlow'),
(17, 'William Wallace'),
(18, 'Han Solo'),
(19, 'Oskar Schindler'),
(20, 'V.A. Vandevere'),
(21, 'Coccinelle'),
(22, 'Cliff Booth'),
(23, 'Aldo Raine');